.github/workflows/ci.yml

Pushes the `latest` tag (= fedora 34) again.
closes #11

Update 'latest' tag again

---

.github/workflows/ci.yml
fedora-33/Dockerfile

Add already supported Distro Fedora FC33 as i'm in need of more A/B testing when it comes to the Host OS.

Add fc33 image for A/B testing purposes

---

.github/workflows/ci.yml

Use full paths only and read credentials from stdin.

Workflow configuration enhancements

---

fedora-32/Dockerfile
fedora-33/Dockerfile
fedora-34/Dockerfile
fedora-35/Dockerfile

Install `langpacks-en` package and explicitly set encoding to fix locale issues (... hopefully 🤞).

Locale settings

---

fedora-32/Dockerfile
fedora-33/Dockerfile
fedora-34/Dockerfile
fedora-35/Dockerfile

Fix dnf remove

---

.github/workflows/ci.yml

Updates hadolint to latest version (incl. update of hadolint itself).

Update hadolint-action to 1.7.0

---

.github/workflows/ci.yml

Extract Hadolint to a separate job and use recursion instead of naming each Dockerfile to analyse.

Extract Hadolint stage

---

.github/workflows/ci.yml
fedora-32/Dockerfile
fedora-33/Dockerfile
fedora-34/Dockerfile
fedora-35/Dockerfile

Full qualified images and trusted registry

---

.github/workflows/ci.yml

Updates hadolint-action to latest release.

Update haodlint-action to latest 2.1.0 release

---

.github/workflows/ci.yml

Minor formatting change for better readability.

Formatting

---

fedora-34/Dockerfile
fedora-35/Dockerfile
fedora-36/Dockerfile

Changes the UID to 2000 (#50) and sets the Git default branch (#52).
#closing #50, #52

UID change and Git default branch

---

yocto-fc/Dockerfile

Adds 32-bit dependencies necessary for QtWebEngine.
closes #59

Add 32-bit dependencies for QtWebEninge

---

yocto-fc/Dockerfile

Add missing 64-bit libstdc++-static (#59).

Add 64-bit libstdc++-static

---

yocto-fc/Dockerfile

Latest version of _gitrepo_ is v2.16.7.

Update gitrepo to latest v2.16.7

---

yocto-fc/Dockerfile

Update to latest *gitrepo* release.

Update gitrepo to 2.16.8

---

.github/workflows/ci.yml
README.md

Adds Fedora 37 build.
closes #63

Add Fedora 37 image build

---

yocto-fc/Dockerfile

Remove duplicated entry

---

.github/workflows/ci.yml

The new version finally fixes an annoying output bug.

Update hadolint-action to 3.1.0

---

.github/workflows/ci.yml
README.md

Fedora 38 image

---

yocto-fc/Dockerfile

Updates repotool to it's latest version.

Update repotool to 2.31.1

---

yocto-fc/Dockerfile

Required to translate .po files to binary message catalog

Add gettext to image

---

yocto-fc/Dockerfile

Installs updates on each build (#88).

Build with updates

---

yocto-fc/Dockerfile

Updates gitrepo to it's latest release.

Update gitrepo 2.32.2

---

.github/workflows/ci.yml
README.md

EOL Fedora 36

---

.github/workflows/ci.yml
README.md

Add Fedora 41 based image

---

.github/workflows/ci.yml
README.md

Beta of Fedora 42 based image (#115).

Add Fedora 42 based image (beta)
