jhnc-oss/yocto-image

- Dockerfile
Add tree tool to the list of packages that get installed in base image
as it is of great help to get a brief overview regarding the plethora
of recipes and layers in the Yocto build container.
> Add package tree to list of install targets

- .github/workflows/ci.yml
Updates Hadolint Action to 1.6.0 which ships the latest linter version.
> Update Hadolint Action to 1.6.0

- .github/workflows/ci.yml
- README.md
- fedora-32/Dockerfile
- fedora-35/Dockerfile
Adds Fedora 35 image (#17). Since it's very new, I'd suggest to keep `latest` on 34 for now.
> Add Fedora 35 image

- fedora-32/Dockerfile
- fedora-33/Dockerfile
- fedora-34/Dockerfile
- fedora-35/Dockerfile
Fixes the package vim package conflict (#26). Since this a known issue for various fedora versions, it's backported to all versions - even though they are not affected at the moment.
closes #26
> Fix package Fedora 35 conflict

- fedora-32/Dockerfile
- fedora-33/Dockerfile
- fedora-34/Dockerfile
- fedora-35/Dockerfile
`localedef` silently fails and causes errors when starting the container.
closes #29
> Remove localedef

- README.md
Fedora 33 is EOL now.
closes #24
> EOL Fedora 33

- .github/workflows/ci.yml
Removes builds of EOL Fedora versions. Dockerfiles and images in the registry are still available, but builds don't make sense since there are no updates any more.
> Remove Fedora 32 and 33 builds

- .github/workflows/ci.yml
- .hadolint.yml
Sets `trusted-registries` for all execution types, not just CI.
> Move trusted-registries to config file

- fedora-34/Dockerfile
- fedora-35/Dockerfile
Installs `repo`; git configs are necessary to avoid interactive settings (#45).
:information_source: No backported to EOL Dockerfiles (< 34)
> Install 'repo'

- .github/workflows/ci.yml
- README.md
- fedora-36/Dockerfile
Adds the Fedora 36 image (#40).
It's marked as beta for now; the final end user release date is planed for ~~26.04.2022~~ ~~03.05.2022~~ 10.05.2022.
> Fedora 36 (Beta)

- README.md
Fedora 36 is stable already (#43).
> Move Fedora 36 image out of Beta

- .github/workflows/ci.yml
- README.md
Marks `latest` as EOL and removes it's build (#48). The tag should be removed after some grace period to avoid usages without an explicit version.
> EOL 'latest'

- README.md
`latest` is no longer available (see #48).
> Remove no longer available 'latest' from docs

- .github/workflows/ci.yml
Updates hadolint-action to it's latest release, featuring hadolint 2.12.
> Update hadolint-action to 3.0.0

- README.md
List the Fedora 34 based image as deprecated.
> Deprecate Fedora 34 based image

- README.md
Stable Fedora 38 is available (#73).
> Remove 'Beta' from FC38 image

- README.md
Deprecates Fedora 35 image.
closes #77
> Deprecate Fedora 35 image

- yocto-fc/Dockerfile
gettext isn't needed after all as it can be used in yocto recipes through "inherit gettext"
> Remove gettext from image

- yocto-fc/Dockerfile
devtool fails during git checkout as branch contains ansi escape sequences (**?[32mdevtool?[m**) as depicted below:
```
INFO: Updating patch 0001-update.patch
Traceback (most recent call last):
File "<path/to>/devtool", line 334, in <module>
ret = main()
File "<path/to>/devtool", line 321, in main
ret = args.func(args, config, basepath, workspace)
File "<path/to>/devtool/standard.py", line 1856, in update_recipe
updated, _, _ = _update_recipe(args.recipename, workspace, rd, args.mode, args.append, args.wildcard_version, args.no_remove, args.initial_rev, dry_run_outdir=dry_run_outdir, no_overrides=args.no_overrides, force_patch_refresh=args.force_patch_refresh)
File "<path/to>/standard.py", line 1828, in _update_recipe
bb.process.run('git checkout %s' % startbranch, cwd=srctree)
File …
```
> Disable color.ui of gitconfig as it breaks devtool

- .github/workflows/ci.yml
- README.md
Updates documentation and removes the build of Fedora 34 and 35.
> EOL Fedora 34 and 35 images

- yocto-fc/Dockerfile
Remove contradicting dnf statement: vim-minimal was removed and later installed again.
> Remove contradicting dnf statement

- yocto-fc/Dockerfile
change the custom uid and gid to the standard uid/gid for the first user on a fedora image. This helps to reduce changes done to the upstream distro image.
> Change yocto uid and gid

- .github/workflows/ci.yml
- README.md
Builds a Fedora 39 based image.
closes #91
> Add Fedora 39 image 

- README.md
I'd suggest we deprecate the Fedora 36 image. This is a documentation only change for now, the build etc. remains unchanged. However, we should consider moving FC36 to EOL in the not too far away future.
> Deprecate Fedora 36 based image

- .github/workflows/ci.yml
- README.md
Fedora 37 is EOL and we do not use it much anyway.
> EOL Fedora 37 image

- yocto-fc/Dockerfile
Removes x86 support related packages (closes #100).
This affects only current images, listed in the readme.
> Remove x86 support

- .github/workflows/ci.yml
- README.md
- yocto-fc/Dockerfile
Adds a Fedora 40 based image, marked as *Beta* for now (closes #97).
Installation of setuptools is necessary at least on FC40 to fix a 'No module named pkg_resources' error.
> Fedora 40 based image

- README.md
While not listed officially, it works without issues so far (#97, #103).
> Move Fedora 40 based image out of beta

- yocto-fc/Dockerfile
Add krb5, python3-devel,toml to list of default packages to provide built-in tools without depending on soon to be vanished upstream feeds for older releases such as FC38.
> Provide krb5 and toml by default

- yocto-fc/Dockerfile
The [required packages list](https://docs.yoctoproject.org/ref-manual/system-requirements.html#fedora-packages) of the manual (version 5.1 Styhead) contains libacl, which isn't present in our packages.
There are no issues so far, but since the manual explicitly mentions it, there may be a specific reason for its inclusion.
> Add libacl

- .github/workflows/ci.yml
- README.md
Fedora 39 is [EOL since 2024-11-26](https://docs.fedoraproject.org/en-US/releases/eol/).
> EOL Fedora 39 based image

- yocto-fc/Dockerfile
Add cargo, quilt to default installation to avoid the need for an active package feed (especially when it comes to older images such as Fedora Core 38) a.k.a batteries included
Fixes (#112)
> Add cargo, quilt to default installation
